# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/RISC-V/Processor/Processor.cache/wt [current_project]
set_property parent.project_path C:/Projects/RISC-V/Processor/Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Projects/RISC-V/Processor/Processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Projects/RISC-V/Processor/Processor.srcs/sources_1/new/ALUController.v
  C:/Projects/RISC-V/Processor/Processor.srcs/sources_1/new/Controller.v
  C:/Projects/RISC-V/DataMemory_DataPath/DataMemory_DataPath.srcs/sources_1/new/DataMem.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/DataPath.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/FlipFlop.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/HalfAdder.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/ImmGen.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/InstMem.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/MUX21.v
  C:/Projects/RISC-V/RegFile_InstrMem/RegFile_InstrMem.srcs/sources_1/new/RegFile.v
  C:/Projects/RISC-V/DataMemory_DataPath/DataMemory_DataPath.srcs/sources_1/new/alu_32.v
  C:/Projects/RISC-V/Processor/Processor.srcs/sources_1/new/processor.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top processor -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
